SET SERVEROUTPUT ON;

DECLARE

ctx DBMS_XMLGEN.CTXHANDLE;
XMLOUT CLOB;

BEGIN
      ctx := DBMS_XMLGEN.newContext('SELECT A.CLIENTE.NOME AS CLIENTE_NOME, A.TIPO AS TIPO, A.IDADE AS IDADE FROM TB_ANIMAL A');
      DBMS_XMLGEN.setRowsetTag(ctx, 'LISTA_ANIMAIS');
      DBMS_XMLGEN.setRowTag(ctx, 'ANIMAL');
      XMLOUT := DBMS_XMLGEN.getXML(ctx);
      DBMS_OUTPUT.PUT_LINE(XMLOUT);
      DBMS_XMLGEN.closeContext(ctx);
END;
/
